name: NPM Version Bump

on:
  pull_request:
    types:
      - closed
    branches:
      - main-npm
  push:
    branches:
      - main-npm

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Bump version and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION_BUMP="patch"
          if [[ "${{ github.event.pull_request.title }}" == *"[major]"* ]]; then
            VERSION_BUMP="major"
          elif [[ "${{ github.event.pull_request.title }}" == *"[minor]"* ]]; then
            VERSION_BUMP="minor"
          fi
          npm version $VERSION_BUMP -m "chore(release): %s"
          git push
