name: Version Bump

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find latest version tag
        id: find-tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Determine version bump
        id: version-bump
        run: |
          message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $message == major* ]]; then
            semver bump major > version.txt
          elif [[ $message == minor* ]]; then
            semver bump minor > version.txt
          else
            semver bump patch > version.txt
          fi

      - name: Install semver
        run: npm install -g semver

      - name: Create tag
        if: success()
        run: |
          new_version=$(cat version.txt)
          git tag $new_version
          git push origin $new_version
