name: Version Bump

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find latest version tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "{name}={$tag}" >> $GITHUB_OUTPUT

      - name: Install semver
        run: npm install -g semver

      - name: Determine version bump
        id: version-bump
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          semver -i patch ${tag} >> version.txt
#          message=$(git log --format=%B -n 1 2>/dev/null || echo "initial")
#          if [[ $message == major* ]]; then
#            semver bump major > version.txt
#          elif [[ $message == minor* ]]; then
#            semver bump minor > version.txt
#          else
#            semver bump patch > version.txt
#          fi

      - name: Create tag
        if: success()
        run: |
          new_version=$(cat version.txt)
          git tag $new_version
          git push origin $new_version
